import { ProductType } from '../Model/product-type';

export const productDataList: ProductType[] = [
  {
    id: '1',
    title: 'ไอแพด-1',
    imgCover: '/assets/5s-1.jpeg',
    allImg: [
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
      '/assets/9g-1.jpeg',
      '/assets/9g-2.jpeg',
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
      '/assets/9g-2.jpeg',
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
    ],
    price: 186,
    inventory: 25,
  },
  {
    id: '2',
    title: 'ไอแพด-2',
    imgCover: '/assets/5s-2.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 199,
    inventory: 1,
  },
  {
    id: '3',
    title: 'ไอแพด-3',
    imgCover: '/assets/9g-1.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 129,
    inventory: 6,
  },
  {
    id: '4',
    title: 'ไอแพด-4',
    imgCover: '/assets/9g-2.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 56,
    inventory: 1,
  },
  {
    id: '5',
    title: 'ไอแพด-2',
    imgCover: '/assets/logo.png',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 199,
    inventory: 51,
  },
  {
    id: '6',
    title: 'ไอแพด-1',
    imgCover: '/assets/5s-1.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 186,
    inventory: 9,
  },
  {
    id: '7',
    title: 'ไอแพด-2',
    imgCover: '/assets/5s-2.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 199,
    inventory: 7,
  },
  {
    id: '8',
    title: 'ไอแพด-3',
    imgCover: '/assets/9g-1.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 129,
    inventory: 8,
  },
  {
    id: '9',
    title: 'ไอแพด-4',
    imgCover: '/assets/9g-2.jpeg',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 56,
    inventory: 6,
  },
  {
    id: '10',
    title: 'ไอแพด-2',
    imgCover: '/assets/logo.png',
    allImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    price: 199,
    inventory: 55,
  },
];
