import { ProductType } from '../Model/product-type';

export const productDataList: ProductType[] = [
  {
    Id: 1,
    Title: 'ไอแพด-1',
    ImgCover: '/assets/5s-1.jpeg',
    AllImg: [
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
      '/assets/9g-1.jpeg',
      '/assets/9g-2.jpeg',
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
      '/assets/9g-2.jpeg',
      '/assets/5s-1.jpeg',
      '/assets/5s-2.jpeg',
    ],
    Price: 186,
    Inventory: 25,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 2,
    Title: 'ไอแพด-2',
    ImgCover: '/assets/5s-2.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 199,
    Inventory: 10,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 3,
    Title: 'ไอแพด-3',
    ImgCover: '/assets/9g-1.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 129,
    Inventory: 6,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 4,
    Title: 'ไอแพด-4',
    ImgCover: '/assets/9g-2.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 56,
    Inventory: 1,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 5,
    Title: 'ไอแพด-2',
    ImgCover: '/assets/logo.png',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 199,
    Inventory: 51,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 6,
    Title: 'ไอแพด-1',
    ImgCover: '/assets/5s-1.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 186,
    Inventory: 9,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 7,
    Title: 'ไอแพด-2',
    ImgCover: '/assets/5s-2.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 199,
    Inventory: 7,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 8,
    Title: 'ไอแพด-3',
    ImgCover: '/assets/9g-1.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 129,
    Inventory: 8,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 9,
    Title: 'ไอแพด-4',
    ImgCover: '/assets/9g-2.jpeg',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 56,
    Inventory: 6,
    Quantity: 0,
    Select: false,
  },
  {
    Id: 10,
    Title: 'ไอแพด-2',
    ImgCover: '/assets/logo.png',
    AllImg: ['/assets/5s-1.jpeg', '/assets/5s-2.jpeg'],
    Price: 199,
    Inventory: 55,
    Quantity: 0,
    Select: false,
  },
];
